#!/usr/bin/env bash
#managing the manage_my_process process
if [ "$1" = "start" ]; then
	./manage_my_process &
	echo "$!" > /tmp/my_process.pid
	echo "manage_my_process started"
elif [ "$1" = "stop" ]; then
	cat /tmp/my_process.pid | xargs kill
	rm /tmp/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" = "restart" ]; then
	cat /tmp/my_process.pid | xargs kill
	rm /tmp/my_process.pid
	./manage_my_process &
	echo "$!" > /tmp/my_process.pid
	echo "manage_my_process restarted"
else
	echo "manage_my_process {start|stop|restart}"
fi
